name: Flutter Build (Self Healing)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      # ✅ Auto-fix pubspec.yaml formatting issues
      - name: Auto-fix pubspec.yaml
        run: |
          echo "Fixing pubspec.yaml formatting..."
          sed -i 's/\t/  /g' pubspec.yaml
          yq e '.' pubspec.yaml -i || true

      - name: Clear pub cache
        run: flutter pub cache repair

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
